from glob import glob
import smtplib
import threading



class recepient :
    s = smtplib.SMTP("smtp.gmail.com", 587)
    s.starttls()
    senderEmail = "" #Email Address of Account fro which mail needs to be sent.
    otp = "" #Password Generated by the mailing service for that specific account
    s.login(senderEmail,otp)
    
    
    def __init__(self, name, email) :
        self.name = name
        self.email = email
        self.message = f"Hey {self.name}, This message is for you!"
    
    def sendEmail(self) :
        global senderEmail
        global otp
        s = smtplib.SMTP("smtp.gmail.com", 587)
        s.starttls()
        s.login(senderEmail,otp)
        s.sendmail(senderEmail, self.email,self.message)
        s.quit()
    

if __name__ == "__main__" :
    while True  :
        num = input("Enter the number of recepients : ")
        if not num.isdigit() or num == 0:
            print("Enter a valid number >= 1, Try Again !")
            continue 
        else :
            num = int(num)
            break
    
    receivers = {}
    threads =[]
    for i in range(num) :
        name = input(f"Enter name of {i + 1}th person : ")
        email = input(f"Enter email of {i + 1}th person : ")
        obj_name = f"{name}_{i+1}"
        receivers[obj_name] = recepient(name, email)
        thread = threading.Thread(
            target= receivers[obj_name].sendEmail,
            args=()
        )
        threads.append(thread)
    
    for thread in threads :
        thread.start()
    for thread in threads :
        thread.join()
        
    